### ISSUE TITLE
Redirect URIs duplicating context root when changed in Quarkus with `quarkus.http.root-path`

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-renarde#104]
Not sure how to explain this but, I changed my context path from `/` to `/support` so my urls look like `http://localhost:8080/support` to access my HTML/QUTE/RENARDE app.

`quarkus.http.root-path=/support`

When I generate the redirect URIS according to the docs, I'm getting duplicate context roots:

The code below generates a URI of: `http://localhost:8080/support/support/`

```
 // All good, set the JWT cookie
        NewCookie cookie = security.makeUserCookie(user);
        return Response.seeOther(Router.getURI(Application::index)).cookie(cookie).build();
```

All my paths on my endpoints are defined as @Path("") at the top of the class and @Path("/") for index page and @Path("/login") for example. All of them start with '/'

Any ideas?

**Comment by FroMage** [comment]
OK, that one is interesting. `Router.getURI()` returns the proper `/support/` path, but then, `Response.seeOther` adds another layer of `/support` for some reason. I'll have to check RESTEasy Reactive, see why it does that.

**Comment by FroMage** [comment]
I've fixed this in `main` and `1.x`
