### ISSUE TITLE
Renarde and Keycloak 

### ISSUE THREAD

**Issue by dwamara** [quarkiverse/quarkus-renarde#135]
It's not an issue but more of a question but I couldn't find where to ask it.

Is there any way to use Keycloak as OIDC solution with Renarde? It is something that I would like to do for a company I am building different solutions for but couldn't find nothing in the documentation.

D.

**Comment by FroMage** [comment]
It should work the same as other OIDC providers, no? You can probably follow the regular Quarkus docs for it: https://quarkus.io/guides/security-keycloak-authorization

Let me know if you run into any issue or if there's anything we can improve :)

**Comment by FroMage** [comment]
I'm going to close this issue, but let me know if you ran into any issue.
