### ISSUE TITLE
Incorrect URL Encoding for Optional Parameters

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-renarde#151]
Hi there,

I hope you're doing well. I encountered an issue while using the quarkus-renarde project. When binding Optional parameters and performing a redirect, the URL encoding for the Optional values seems to be incorrect, resulting in unexpected behavior.

Steps to Reproduce:

1. Define a method with Optional parameters like this:

```java
public TemplateInstance shops(@RestQuery(value = "id") Optional<Long> optionalId, @RestQuery(value = "page") Optional<Integer> optionalPageNumber) {
  // Method implementation...
}
```

2. Call the shops method from another method for a redirect:
```java
return this.shops(Optional.of(shop.id), Optional.empty());
```

The URL is generated incorrectly, and the Optional values are not properly encoded, leading to URLs like:

http://localhost:8080/admin/shops?id=Optional%5B501%5D&page=Optional.empty

where %5B and %5D represent [ and ], respectively, and 501 is the id of the shop.

Thank you.

**Comment by FroMage** [comment]
Ah, indeed I don't think we handle `Optional` at all. We need to fix this.

**Comment by gbourant** [comment]
Also when attempting to inject a URI with `{uriabs:AdminShopResource.shopsNew(it.id)}` into a Qute template while the parameter is an `Optional` one the following error is encountered:

`java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.util.Optional`

**Comment by FroMage** [comment]
Fixed, thanks for reporting!
