### ISSUE TITLE
Wrong Content-Type header when using fragments

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-renarde#165]
When the response is an HTML fragment it adds the `Content-Type:text/plain;` instead of  `Content-Type:text/html;` so the page is not rendered properly.  

```java
@Path("/")
public class HelloResource extends io.quarkiverse.renarde.Controller {

    public io.quarkus.qute.TemplateInstance index() {
        return HtmlTemplate.index();
    }

    public io.quarkus.qute.TemplateInstance fragment() {
        return HtmlTemplate.index$fragment();
    }

}
```

```html
<p style="color:red">from qute index</p>

{#fragment id='fragment' rendered=false}
 <p style="color:red">the fragment</p>
{/fragment}
```

```java
@CheckedTemplate
public class HtmlTemplate {

    public static native TemplateInstance index();

    public static native TemplateInstance index$fragment();

}
```

**Comment by FroMage** [comment]
This sounds like a generic Qute bug, no, @mkouba ? Perhaps because we don't set `VARIANTS` on the fragments, but only on the template? Then the `TemplateResponseFilter` won't be able to set the `MediaType` properly.

**Comment by mkouba** [comment]
> This sounds like a generic Qute bug, no, @mkouba ? Perhaps because we don't set `VARIANTS` on the fragments, but only on the template? Then the `TemplateResponseFilter` won't be able to set the `MediaType` properly.

You're right. The fragments are not fully integrated with resteasy-qute/type-safe templates yet. I'll try to propose a fix this week.

**Comment by FroMage** [comment]
Great, thanks. Should I open an issue on Quarkus?

**Comment by mkouba** [comment]
> Great, thanks. Should I open an issue on Quarkus?

https://github.com/quarkusio/quarkus/pull/35841 :smile:

**Comment by FroMage** [comment]
You're too fast for me. Thanks a lot, I'll close this.
