### ISSUE TITLE
_renarde_language cookie is not respected by Hibernate validation

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-renarde#167]
Hibernate validation ignores the _renarde_language cookie.

**Comment by FroMage** [comment]
Oh yeah, that's surely true. Do you have a reproducer with internationalised messages? I've never tried this.

**Comment by gbourant** [comment]
Sure, you can check it here: https://github.com/gbourant/validation

**Comment by FroMage** [comment]
Thanks!

**Comment by FroMage** [comment]
Thanks. Can be done by implementing a `LocaleResolver` as indicated in https://quarkus.io/guides/validation#validation-and-localization, as done in Quarkus for RESTEasy Reactive and GraphQL. I can add one for Renarde, should be easy.

**Comment by FroMage** [comment]
Well, I also have to check _where_ it's getting those localised messages from as well.

**Comment by gbourant** [comment]
It works as expected, thank you.
