### ISSUE TITLE
Merge i18n messages files

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-renarde#172]
Assume you have following projects:  

<pre>
.
├── admin
├── project-a
├── project-b
├── project-c
└── project-d
</pre>

In this setup, "admin" project acts as a foundational dependency for all other projects, resulting in the other projects overriding the message files initially defined in "admin."

Now, here's a feature request: Merge the message files from the "admin" project with those of each individual project.

**Comment by FroMage** [comment]
That's interesting. So, each project is a Renarde project? So you want the message bundles to compose together, then? Or make it so each project only sees its own resource bundles?

**Comment by gbourant** [comment]
In my case each project is a Renarde project and each one has a dependency to the admin project (admin is also a Renarde project).

So, 

`project-a` has a  dependency to `admin` project,
`project-b` has a  dependency to `admin` project,
`project-c` has a  dependency to `admin` project,
`project-d` has a  dependency to `admin` project.

With this setup then `project-a` should be able to see admin's and it's resource bundles (composed together) but not project-b-c-d since it does not have a dependency to those.

**Comment by FroMage** [comment]
Oh, OK, I see. Yeah, this makes sense.

**Comment by gbourant** [comment]
Well, seems i didn't describe why i opened the ticket in the first place, so here we go.

When i run the `project-a` project which has a dependency to the `admin` project, all the admin's messages resource bundles are not available.

So the following image is when i run quarkus:dev in `project-a` which displays the login page which exists in `admin` project. (The same page is displayed correctly if i run `admin` with quarkus:dev)


![image](https://github.com/quarkiverse/quarkus-renarde/assets/9791051/fdc1d7e6-4a1b-473b-8f8b-eae11e8bf81e)
