### ISSUE TITLE
IllegalArgumentException when adding renarde as a dependency

### ISSUE THREAD

**Issue by dwamara** [quarkiverse/quarkus-renarde#18]
I've just create a simple Quarkus project which started fine. As soon as I added the renarde dependency (version 1.0.0) in the pom.xml, I've started getting following error which doesn't seem to disappear no matter what I do:

`
022-05-09 10:09:48,360 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.qute.deployment.QuteProcessor#collectTemplates threw an exception: java.lang.IllegalArgumentException
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.relativize(ZipPath.java:230)
	at io.quarkus.qute.deployment.QuteProcessor.scan(QuteProcessor.java:2301)
	at io.quarkus.qute.deployment.QuteProcessor.scan(QuteProcessor.java:2313)
	at io.quarkus.qute.deployment.QuteProcessor.collectTemplates(QuteProcessor.java:1291)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:330)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
	at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:95)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:485)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:68)
	at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:142)
	at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:97)
	at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:132)
	at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)`

Any idea how to fix this? I used Quarkus 2.8.2.Final and then saw that the 2.8.3.Final was out and moved to it but without any success.

D.

**Comment by FroMage** [comment]
What are your Quarkus extensions ?

**Comment by dwamara** [comment]
The dependencies you mean? Here is my dependencies part of the pom file
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0">

    <properties>
        <java.version>11</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <quarkus.version>2.8.3.Final</quarkus.version>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
    </properties>

    <groupId>com.dwitech.saas.assurtech</groupId>
    <artifactId>assurtech-frontend</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-universe-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-json</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-gelf</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-container-image-jib</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mysql</artifactId>
        </dependency>

        
        <dependency>
            <groupId>io.quarkiverse.renarde</groupId>
            <artifactId>quarkus-renarde</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.renarde</groupId>
            <artifactId>quarkus-renarde-oidc</artifactId>
            <version>1.0.0</version>
        </dependency>
        
        
        <dependency>
            <groupId>com.dwitech.saas.assurtech</groupId>
            <artifactId>assurtech-shared</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.11</version>
        </dependency>
    </dependencies>
</project>`

**Comment by FroMage** [comment]
I did see that exception when running tests from Eclipse. But never from Maven. I assumed a classpath issue then.

I just created an empty project with your extension list, and I don't get that exception, so can you give me a project to reproduce it?

What OS are you using?

**Comment by dwamara** [comment]
I am using macOS Monterey 12.3.1. I just made https://github.com/dwamara/renarde_bug_8, I got the same result: everything is starting fine until I had the renarde dependencies.

**Comment by FroMage** [comment]
With your application I'm getting this:

```
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkiverse.renarde.oidc.RenardeOidcHandler and qualifiers [@Default]
	- java member: io.quarkiverse.renarde.oidc.impl.RenardeSecurityController#oidcHandler
	- declared on CLASS bean [types=[io.quarkiverse.renarde.oidc.impl.RenardeSecurityController, java.lang.Object, io.quarkiverse.renarde.Controller], qualifiers=[@Default, @Any], target=io.quarkiverse.renarde.oidc.impl.RenardeSecurityController]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:411)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:527)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:263)
		... 13 more
	Suppressed: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkiverse.renarde.oidc.RenardeUserProvider and qualifiers [@Default]
	- java member: io.quarkiverse.renarde.oidc.RenardeSecurity#userProvider
	- declared on CLASS bean [types=[io.quarkiverse.renarde.oidc.RenardeSecurity, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkiverse.renarde.oidc.RenardeSecurity]
		at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:411)
		at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:527)
		at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:263)
		... 13 more
```

Which means you're missing implementations of these two types.

**Comment by dwamara** [comment]
Strange, isn't that following dependency: 
`<dependency>
            <groupId>io.quarkiverse.renarde</groupId>
            <artifactId>quarkus-renarde-oidc</artifactId>
            <version>1.0.0</version>
        </dependency>

`
if that's the case, it is already in the pom file (lines 66-70)

**Comment by FroMage** [comment]
That's due to this dependency, yes. If you have this dependency, you must provide implementations of those two types. But it doesn't look like you have them.

**Comment by dwamara** [comment]
I've just removed that dependency and still got the same error.

**Comment by dwamara** [comment]
Hi Stéphane, no news about the problem?

**Comment by dwamara** [comment]
Yes I do

**Comment by FroMage** [comment]
I just tried your repo and it starts for me.

**Comment by dwamara** [comment]
Hi @FroMage , could you please try to see if you can start agro-commande-frontend under https://github.com/dwamara/agro-command. It's part of a multi project so I took out the other projects that are not necessary and tweaked to pom file to include everything needed.

I get the error I previously described in it. 

Regards,
Daniel
