### ISSUE TITLE
Feature request: CRUD Admin

### ISSUE THREAD

**Issue by preslavrachev** [quarkiverse/quarkus-renarde#201]
This one isn't meant as an issue, but rather as a point for discussion. As someone who has been equally versed in the Java and Django worlds, I cannot help but ease with which Django's built in CRUD Admin helps get things done. In my many years as a Java developer, I have only seen a couple half-baked attempts of the same. Probably, because the large majority of Java projects end up being either API-centric, or there is a dedicated frontend team that helps get things done.

Working in a small team, I'd love having the ability to bootstrap projects as quickly as possible. Quarkus + Renarde are already getting 80% of the job done. However, getting the other 20% is often slow and awfully repetitive. I'd love having the possibility of annotating my entities in a certain way, and thus getting an entire administration dashboard for managing things.

The closest thing in the Java realm I have managed to find is this one: https://www.snapadmin.dev/ It is quite promising, but as it is heavily tied to Spring Boot, I doubt it would easily wok on a Quarkus app.

On a scale from 1 to 10, how likely is to every see anything like this coming with Renarde? Or, is an entirely separate Quarkus extension a better idea?

**Comment by gbourant** [comment]
@FroMage has implemented the [backoffice](https://docs.quarkiverse.io/quarkus-renarde/dev/advanced.html#_backoffice) does that help you?

**Comment by preslavrachev** [comment]
Like, honestly, someone worked on this? This is fantastic news! It seems a bit more rudimentary than the Django Admin and SnapAdmin, but I am sure it will get better over time. Considering how much time we've been planning to invest on building it ourselves, it's a huge time saver.

@gbourant Thanks for the tip! We've been using an older version of Renarde, but recently upgraded everything to Quarkus v3, so there's a bit to catch up with, it seems. I guess, I've always been looking for something with the name Admin, so Backoffice never registered ;)

I'll give this a try.

**Comment by FroMage** [comment]
Try it and let us know. It's still beta quality, but hopefully we can collaborate on improving it :)

**Comment by FroMage** [comment]
I'll close this issue then, feel free to open bug reports or improvement requests :)
