### ISSUE TITLE
@Path containing regex breaks Router

### ISSUE THREAD

**Issue by gbourant** [quarkiverse/quarkus-renarde#238]
For the following controller

```java
@Path("/p/pixel")
class PixelResource extends Controller   {

    @GET
    @Path("{token}/{checksum}{extention: (\\.png)?}")
    public Response pixel(@RestPath("token") UUID token, @RestPath("checksum") Integer checksum) {
       return Response.ok().build();
    }
}
```

The falling call `Router.getAbsoluteURI(PixelResource::pixel, UUID.fromString("453f74a6-d1f1-4cca-9322-142f9f46df09"), 477258115)`  returns `http://localhost:8081/p/pixel/453f74a6-d1f1-4cca-9322-142f9f46df09/477258115%7Bextention:%20(%5C.png)?%7D`

It adds the `%7Bextention:%20(%5C.png)?%7D` at the end.

**Comment by FroMage** [comment]
Ouch, this is definitely a bug :(

I wonder where it lies…

**Comment by gbourant** [comment]
I just tried (with correct spelling) and with a new RestPath "extension"
```java

@Path("/p/pixel")
class PixelResource extends Controller   {

    @GET
    @Path("{token}/{checksum}{extension: (\\.png)?}")
     public Response pixel(@RestPath("token") UUID token, @RestPath("checksum") Integer checksum, @RestPath("extension") String extension ) {
       return Response.ok().build();
    }
}

```
and 
`Router.getAbsoluteURI(PixelResource::pixel, UUID.fromString("453f74a6-d1f1-4cca-9322-142f9f46df09"), 477258115 ,".png")` 
returns the same 
`http://localhost:8081/p/pixel/453f74a6-d1f1-4cca-9322-142f9f46df09/477258115%7Bextension:%20(%5C.png)?%7D`

**Comment by gbourant** [comment]
The new param is totally ignored, for example the result of `Router.getAbsoluteURI(PixelResource::pixel, UUID.fromString("453f74a6-d1f1-4cca-9322-142f9f46df09"), 477258115 ,"SOME_RANDOM_DATA")` is the same as before `http://localhost:8081/p/pixel/453f74a6-d1f1-4cca-9322-142f9f46df09/477258115%7Bextension:%20(%5C.png)?%7D`

**Comment by FroMage** [comment]
OK, it's a Quarkus REST bug, I'll report it upstream.

**Comment by FroMage** [comment]
Reported at https://github.com/quarkusio/quarkus/issues/42249
