### ISSUE TITLE
How to configure opensource OIDC providers?

### ISSUE THREAD

**Issue by sag1** [quarkiverse/quarkus-renarde#25]
Hello,
I am really unsatisified with the choice of preconfigured providers. Maybe it's easy for those who are using these providers. There is no documentation on how to configure OpenSource OIDC providers. I think that it will be better without this list of known providers and give more possibility for opensource providers.

quarkus.oidc.provider=xxxx
quarkus.oidc.client-id=<Client ID>
quarkus.oidc.credentials.secret=<Client Secret>

Any explication why offering only the fixed providers and how can it be used for other unknown provider?

**Comment by FroMage** [comment]
You can use other providers, the Quarkus OIDC documentation explains it all: https://quarkus.io/guides/security-openid-connect-web-authentication

Let me know if you run into issues.
