### ISSUE TITLE
java.util.Date ParamConverterProvider overriding custom one

### ISSUE THREAD

**Issue by tmulle** [quarkiverse/quarkus-renarde#65]
I was trying to use my custom `java.util.Date` `ParamConverterProvider` in my application but it is never being called, well, I should say it's not being passed in any instances of `java.util.Date` from my form POJO that I pass into my JAX-RS methods with the `@BeanParam` annotation.

I have the need to use a POJO for my HTML FORM which uses the `url-encoded` method so I don't have to list out every single parameter in my method signature.

I made a POJO like this:

```java
public class UserFormData {

 @FormParam("expireDate")
 Date expireDate;

 @FormParam("firstName")
 String firstName;

 .... More Fields

}
```

Then in my `POST` method in my controller I have something like:

```java
@POST
public void handle(@BeanParam UserFormData userData) {
  log.info("Got my data: {}", userData);
}
```
I posted this to the Quarkus StackOverflow group and they responded telling me to use the `@BeanParam` annotation. This works fine as long as I don't have any Date parameters in my bean (which is not what I want)

https://stackoverflow.com/questions/73912142/how-to-handle-form-url-encoded-to-pojo-with-quarkus/73931334#73931334

Doing an experiment and eliminating dependencies out of my project I found that removing Renarde itself fixes the issue BUT I need to use it :)

Looking at the source for Renarde it looks like you're registering a default provider for `java.util.Date` already?
https://github.com/quarkiverse/quarkus-renarde/blob/main/runtime/src/main/java/io/quarkiverse/renarde/util/MyParamConverters.java

Can I override this version to use my version so I can define my own date formats? I don't see a priority attribute on the Provider annotation.

When I leave the Date fields in my class I get a `400 Bad Request` response and no errors on the server. Commenting out the date fields lets the form submission process but obviously is not what I want since I can't use my Date fields.

Thanks!

**Comment by FroMage** [comment]
What I can do is make sure the renarde provider has a lower priority than the default one.

Meanwhile, as a workaround, you can add  `@Priority(Priorities.USER-1)` to your `ParamConverterProvider`, your provider should be used first.
