### ISSUE TITLE
How to define the home.html page ?

### ISSUE THREAD

**Issue by cmoulliard** [quarkiverse/quarkus-renarde#69]
## Question

How can we define the home.html page which is pointing to `resources/templates/home.html`?

I tried using an ApplicationScope class and `@Resource(name="home.html")` without success 
```
package io.halkyon;

import io.quarkus.qute.Template;

import javax.annotation.Resource;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

@ApplicationScoped
public class App {

    @Inject
    @Resource(name="home.html")
    Template main;
}
```

**Comment by FroMage** [comment]
You should rather try:

```java
public class Application extends Controller {
 @CheckedTemplates
 public static class Templates {
  public static native TemplateInstance index();
 }

 @Path("/")
 public TemplateInstance index(){
  return Templates.index();
 }
}
```

For your template in `resources/templates/Application/index.html`

**Comment by cmoulliard** [comment]
> For your template in `resources/templates/Application/index.html`

But then you cannot declare a page at the root of the templates such as `resources/templates/index.html` ?

**Comment by FroMage** [comment]
You can, and I can tell you how, but what's the point?

**Comment by FroMage** [comment]
This should use `resources/templates/index.html`, but I'm not sure why you'd want to go against the recommended way of doing things in Renarde?

```java
 @CheckedTemplates
 public static class Templates {
  public static native TemplateInstance index();
 }

public class Application extends Controller {
 @Path("/")
 public TemplateInstance index(){
  return Templates.index();
 }
}
```

**Comment by cmoulliard** [comment]
> but what's the point?

To have a home page containing menus, submenus, ... from where we can access the different parts of the application which are then managed by different templates/controlers (e.g resources/templates/claim, resources/templates/service, resources/templates/serviceregistration, ...)

**Comment by cmoulliard** [comment]
> This should use `resources/templates/index.html`,

That fails
```
Caused by: io.quarkus.qute.TemplateException: No template matching the path App/index could be found for: io.halkyon.App$Templates.index
        at io.quarkus.qute.deployment.QuteProcessor.collectCheckedTemplates(QuteProcessor.java:348)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
```
if we declare a class as
```
package io.halkyon;

import io.quarkiverse.renarde.Controller;
import io.quarkus.qute.CheckedTemplate;
import io.quarkus.qute.TemplateInstance;

import javax.ws.rs.Path;

public class App extends Controller {
    @CheckedTemplate
    public static class Templates {
        public static native TemplateInstance index();
    }

    @Path("/")
    public TemplateInstance index(){
        return Templates.index();
    }
}
```

**Comment by FroMage** [comment]
Well yeah, don't declare it nested if you want it as toplevel.

**Comment by FroMage** [comment]
> To have a home page containing menus, submenus, ... from where we can access the different parts of the application which are then managed by different templates/controlers (e.g resources/templates/claim, resources/templates/service, resources/templates/serviceregistration, ...)

This is not how to do it, check out our sample Todo application, and use an include to that all your pages have the same structure.

**Comment by cmoulliard** [comment]
> This is not how to do it, check out our sample Todo application, and use an include to that all your pages have the same structure.

If I understand you correctly, the only way to make it working is to :

1. Create a `home, welcome, main, etc.html` page at the root of `resources/templates/home.html`
2. Under each template controller (e.g application) which includes pages (index, about, ...) add as 1st line `{#include main.html }`

Is it correct ?

**Comment by FroMage** [comment]
No, check out the todo app structure :)
You want a single main template, and extend it from all the other pages:

```
- main.html
- Application/index.html
- Application/about.html
- Application/welcome.html
- Orders/index.html
- Customers/index.html
- Admin/something.html
```

**Comment by FroMage** [comment]
> Create a home, welcome, main, etc.html page at the root of resources/templates/home.html

I really mean "No", because at the toplevel you should only put your main templates. All the other pages are in subfolders that correspond to their controllers.
