### ISSUE TITLE
validation errors not copied to flash

### ISSUE THREAD

**Issue by nderwin** [quarkiverse/quarkus-renarde#82]
Manually added validation errors added through the `addError(field, message)` method are not copied to the flash error map immediately for use in the response template.

Attached is an example project.  To recreate:

1. ./mvnw clean compile quarkus:dev
2. navigate to http://localhost:8080
3. enter an email address in the registration form, and click Submit
4. on the registration page, do not fill out the name or nickname fields, then click Submit
5. registration page should be displayed again, but with error messages about needing to fill out the name or nickname fields;  the error messages are missing

[code-with-quarkus.zip](https://github.com/quarkiverse/quarkus-renarde/files/10100268/code-with-quarkus.zip)

**Comment by FroMage** [comment]
Fixed
